server:
  port: 8080

spring:
  application:
    name: gmaildashboard
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:CAMBIAR_POR_TU_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:CAMBIAR_POR_TU_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google

logging:
  level:
    org.springframework.security: INFO